apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: learnarcab
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-nginx
    spec:
      nodeSelector:
        kind: shared
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: learnarcab
  name: test-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app.kubernetes.io/name: test-nginx
